version: '3.4'

services:
  php:
    image: ${CONTAINER_REGISTRY_BASE}/php
    build:
      context: ./
      target: api_platform_php
    depends_on:
      - db
    volumes:
      - ./:/srv/api:rw,delegated

  nginx:
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    build:
      context: ./
      target: api_platform_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/api/public
    ports:
      - "8080:80"

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
    ports:
      - "25432:5432"
