# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Event,Kernel.php}'
        autoconfigure: true
        autowire: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Converter
    App\Converter\IriConverter:
        decorates: 'api_platform.iri_converter'
        arguments:
            $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_factory'
            $decorated: '@App\Converter\IriConverter.inner'

    # Encrypter
    App\Encrypter\OpenSSLEncrypter:
        arguments:
            $secret: '%env(ENCRYPTER_SECRET)%'

    GuzzleHttp\Client: ~
    GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'
